name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */2 * *'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
#          - { name: i686, bits: 32 }
          - { name: x86_64, bits: 64 }
        build_type:
          - release
          - debug
    steps:
      - name: Checkout build sources
        uses: actions/checkout@v2

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc

      - name: Dump build environment
        shell: msys2 {0}
        run: |
          echo - Windows Environent Variable
          set
          echo - Bash Environent Variable
          export

      - name: Checkout sources
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bgfx.git
          git clone --depth 1 https://github.com/bkaradzic/bx.git
          git clone --depth 1 https://github.com/bkaradzic/bimg.git

      - name: Cache build files
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('lockfile.txt') }}-${{matrix.build_type}}-${{matrix.platform.name}}
          path: |
            */.build

      - name: Compile BX
        shell: msys2 {0}
        env:
          MINGW: /mingw64/
        run: |
          cd bx
          make mingw-gcc-${{matrix.build_type}}${{matrix.platform.bits}}

      - name: Compile BIMG
        shell: msys2 {0}
        env:
          MINGW: /mingw64/
        run: |
          cd bimg
          make mingw-gcc-${{matrix.build_type}}${{matrix.platform.bits}}

      - name: Compile BGFX
        shell: msys2 {0}
        env:
          MINGW: /mingw64/
        run: |
          cd bgfx
          make mingw-gcc-${{matrix.build_type}}${{matrix.platform.bits}}

      - name: List files
        shell: msys2 {0}
        run: ls -R

      - name: Upload executable artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build_type}}-${{matrix.platform.name}}-executable
          path: '*/.build/win64_mingw-gcc/bin/*.exe'

      - name: Upload static library artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build_type}}-${{matrix.platform.name}}-staticlib
          path: '*/.build/win64_mingw-gcc/bin/*.a'

      - name: Upload object artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build_type}}-${{matrix.platform.name}}-object
          path: '*/.build/win64_mingw-gcc/obj/'

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    if: '!cancelled() && success()'
    steps:
      - name: Checkout build sources
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2.0.10
        with:
          path: artifacts

      - name: List files
        working-directory: artifacts
        run: ls -R

      - name: Get date
        run: echo "DATE=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ format('build-{0}', github.run_number) }}
          message: ${{ format('build-{0}', github.run_number) }}

      - name: Create release
        uses: softprops/action-gh-release@v0.1.13
        with:
          name: "${{ format('#{1} {0}', env.DATE, github.run_number) }}"
          tag_name: ${{ format('build-{0}', github.run_number) }}
          files: artifacts/*
          body: |
            ${{ format('Auto-build #{1} at {0} UTC', env.DATE, github.run_number) }}

  create-issue:
    runs-on: ubuntu-latest
    needs:
      - release
      - cleanup
    if: 'always()'
    steps:
      - name: Checkout build sources
        uses: actions/checkout@v2

      - name: Create issue
        uses: nashmaniac/create-issue-action@v1.1
        with:
          token: ${{ github.token }}
          title: Auto Build ${{ '#' }}${{ github.run_number}} Failed
          assignees: ${{ github.actor }}
          labels: build-fail
          body: Auto build(for '${{ github.event_name }}') failed on ${{ github.ref_name }}(${{ github.sha }}), triggered by @${{ github.actor }}. Current run is [${{ github.run_number }}/${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

  cleanup:
    runs-on: ubuntu-latest
    if: 'always()'
    steps:
      - name: Checkout build sources
        uses: actions/checkout@v2

      - name: Delete older build failure issues
        uses: lee-dohm/close-matching-issues@v2
        with:
          token: ${{ github.token }}
          query: 'label:build-fail'

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 15
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
